name: Run Stock Report Daily

on:
  schedule:
    - cron: '0 8 * * *'  # רץ כל יום בשעה 8:00 UTC (11:00 בישראל)
  workflow_dispatch:     # מאפשר הרצה ידנית בלחיצת כפתור

jobs:
  run-stock-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance feedparser vaderSentiment

      - name: Run stock_report.py
        run: python stock_report.py
